import { createElement, useState, useEffect, useRef, type ReactNode } from 'react';
import { X, Loader2, AlertCircle, Inbox, type LucideIcon } from 'lucide-react';
import { useWorkspace } from '../context/WorkspaceContext';
export function PageIntro({ eyebrow, title, description, actions }: { eyebrow?:string; title:string; description?:string; actions?:ReactNode }) {
  return <div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[.16em] text-ink-400">{eyebrow || 'Maple workspace'}</p><h1 className="text-2xl font-semibold tracking-tight text-ink-900 sm:text-[28px]">{title}</h1>{description && <p className="mt-2 max-w-2xl text-sm leading-6 text-ink-500">{description}</p>}</div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</div>;
}
export function StatCard({ label, value, detail, icon:Icon, tone='amber' }: { label:string; value:ReactNode; detail?:string; icon:LucideIcon; tone?:string }) {
  return <div className="metric-card"><div className="mb-4 flex items-center justify-between"><p className="text-xs font-medium text-ink-500">{label}</p><span className={`metric-icon ${tone}`}><Icon size={17}/></span></div><p className="truncate text-[27px] font-semibold tracking-tight text-ink-900">{value}</p>{detail && <p className="mt-2 text-xs text-ink-400">{detail}</p>}</div>;
}
export function Card({ title, subtitle, action, children, className='' }: { title?:string; subtitle?:string; action?:ReactNode; children:ReactNode; className?:string }) {
  return <section className={`workspace-card ${className}`}>{title && <div className="flex items-start justify-between gap-3 border-b border-ink-100 px-5 py-4"><div><h2 className="text-sm font-semibold text-ink-900">{title}</h2>{subtitle && <p className="mt-1 text-xs text-ink-400">{subtitle}</p>}</div>{action}</div>}{children}</section>;
}
export function Badge({ children }: {children:ReactNode}) { const text = String(children); const tone = ['Completed','Paid','Present','Resolved','Active','Approved'].includes(text) ? 'green' : ['Critical','High','Blocked','Absent','Rejected','Inactive'].includes(text) ? 'red' : ['In Progress','Ongoing','In Review','Half Day'].includes(text) ? 'blue' : 'amber'; return <span className={`status-pill ${tone}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{children}</span>; }
export function EmptyState({ title='No records yet', detail='Your records will appear here once you add them.', action }: {title?:string; detail?:string; action?:ReactNode}) { return <div className="flex flex-col items-center px-5 py-14 text-center"><span className="mb-4 rounded-2xl bg-ink-50 p-4 text-ink-400"><Inbox size={25}/></span><h3 className="text-sm font-semibold text-ink-700">{title}</h3><p className="mb-5 mt-2 max-w-sm text-xs leading-5 text-ink-400">{detail}</p>{action}</div>; }
export function WorkspaceStatus() { const { loading, error, refresh } = useWorkspace(); if (loading) return <div className="flex items-center gap-3 py-20 text-sm text-ink-500"><Loader2 className="animate-spin" size={18}/>Loading your workspace...</div>; if (error) return <Card><div role="alert" className="flex flex-col items-start gap-3 p-6"><AlertCircle className="text-signal-red"/><h2 className="font-semibold">We couldn’t load your workspace</h2><p className="text-sm text-ink-500">{error}</p><button className="primary-button" onClick={() => void refresh()}>Try again</button></div></Card>; return null; }
function useDialog(onClose:()=>void, busy:boolean) {
  const element=useRef<HTMLElement>(null); const close=useRef(onClose); const working=useRef(busy);
  close.current=onClose; working.current=busy;
  useEffect(()=>{
    const previous=document.activeElement as HTMLElement | null; const overflow=document.body.style.overflow;
    document.body.style.overflow='hidden';
    const focusable=()=>Array.from(element.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],[tabindex="0"]')||[]);
    focusable()[0]?.focus();
    const onKey=(event:KeyboardEvent)=>{
      if(event.key==='Escape'){event.stopPropagation();if(!working.current)close.current();}
      if(event.key==='Tab') { const controls=focusable();const first=controls[0];const last=controls[controls.length-1];
        if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}
        else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}
      }
    };
    document.addEventListener('keydown',onKey,true);
    return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',onKey,true);previous?.focus();};
  },[]);
  return element;
}
export interface Field { key:string; label:string; type?:string; required?:boolean; options?:{value:string;label:string;scopeId?:string}[]; filterBy?:string; when?:{key:string;value:string}; min?:number; max?:number; hint?:string }
export function RecordForm({ title, description, fields, initial={}, onClose, onSave }: { title:string; description?:string; fields:Field[]; initial?:Record<string,unknown>; onClose:()=>void; onSave:(values:Record<string,unknown>)=>Promise<void> }) {
  const [values, setValues] = useState<Record<string,unknown>>(initial); const [busy,setBusy] = useState(false); const [error,setError] = useState(''); const [reading,setReading]=useState(false); const dialog=useDialog(onClose,busy||reading);
  return <div className="modal-backdrop" onMouseDown={(event) => {if(event.target===event.currentTarget&&!busy)onClose();}}><section role="dialog" aria-modal="true" aria-label={title} ref={dialog} className="modal-sheet"><div className="flex items-start justify-between border-b border-ink-100 p-6"><div><h2 className="text-lg font-semibold">{title}</h2>{description && <p className="mt-1 text-xs text-ink-500">{description}</p>}</div><button type="button" aria-label="Close dialog" disabled={busy} onClick={onClose} className="icon-button"><X size={19}/></button></div>
    <form onSubmit={async(event)=>{event.preventDefault();if(busy||reading)return;setBusy(true);setError('');try{await onSave(values);onClose();}catch(err){setError(err instanceof Error?err.message:'Could not save this record.');}finally{setBusy(false);}}} className="space-y-4 p-6">
      {error && <p role="alert" className="rounded-lg bg-signal-redSoft p-3 text-xs text-signal-red">{error}</p>}
      <div className="grid gap-4 sm:grid-cols-2">{fields.filter((field)=>!field.when||values[field.when.key]===field.when.value).map((field) => <label key={field.key} className={`field-label ${field.type==='textarea'?'sm:col-span-2':''}`}><span>{field.label}{field.required&&<span className="ml-1 text-safety-600">*</span>}</span>{field.type==='file' ? <><input type="file" accept="application/pdf,image/png,image/jpeg" className="field-input" onChange={async(event)=>{const file=event.target.files?.[0];if(!file)return;if(file.size>2*1024*1024||!['application/pdf','image/png','image/jpeg'].includes(file.type)){setError('Choose a PDF, PNG or JPEG up to 2 MB.');event.target.value='';return;}setReading(true);const reader=new FileReader();reader.onload=()=>{setReading(false);setValues((previous)=>({...previous,attachment:reader.result,fileName:file.name}));setError('');};reader.onerror=()=>{setReading(false);setError('Could not read this file.');};reader.readAsDataURL(file);}}/>{!!values.fileName&&<small className="font-normal text-ink-500">{String(values.fileName)} <button type="button" className="ml-2 text-signal-red" onClick={()=>setValues({...values,attachment:null,fileName:''})}>Remove attachment</button></small>}</> : field.options ? <select className="field-input" required={field.required} multiple={field.type==='multiselect'} value={field.type==='multiselect'?(Array.isArray(values[field.key])?values[field.key] as string[]:[]):String(values[field.key]??'')} onChange={(event)=>setValues({...values,...(field.key==='site'?{assignedTo:'',worker:''}:{}),[field.key]:field.type==='multiselect'?Array.from(event.target.selectedOptions).map((option)=>option.value):event.target.value})}>{field.type!=='multiselect'&&<option value="">Choose {field.label.toLowerCase()}</option>}{field.options.filter((option)=>!field.filterBy||!values[field.filterBy]||option.scopeId===values[field.filterBy]).map((option)=><option key={option.value} value={option.value}>{option.label}</option>)}</select> : createElement(field.type==='textarea'?'textarea':'input', { className:'field-input', type:field.type==='textarea'?undefined:field.type||'text', rows:field.type==='textarea'?3:undefined, required:field.required, min:field.min, max:field.max, step:field.type==='number'?'any':undefined, minLength:field.type==='password'?8:undefined, maxLength:field.type==='password'?72:['textarea','url'].includes(field.type||'')?5000:500, value:String(values[field.key]??''), onChange:(event: React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>) => setValues({...values,[field.key]:field.type==='number'?(event.target.value===''?'':Number(event.target.value)):event.target.value}) })}{field.hint&&<small className="font-normal text-ink-400">{field.hint}</small>}</label>)}</div>
      <div className="flex justify-end gap-2 border-t border-ink-100 pt-5"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button type="submit" className="primary-button" disabled={busy||reading}>{busy||reading?<Loader2 className="animate-spin" size={16}/>:null}{reading?'Reading file...':busy?'Saving...':'Save record'}</button></div>
    </form></section></div>;
}
export function ConfirmDialog({ title, message, onClose, onConfirm }: {title:string;message:string;onClose:()=>void;onConfirm:()=>Promise<void>}) { const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const dialog=useDialog(onClose,busy); return <div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label={title} ref={dialog} className="modal-sheet max-w-md p-6"><h2 className="font-semibold">{title}</h2><p className="my-4 text-sm leading-6 text-ink-500">{message}</p>{error&&<p role="alert" className="mb-4 text-xs text-signal-red">{error}</p>}<div className="flex justify-end gap-2"><button className="secondary-button" disabled={busy} onClick={onClose}>Cancel</button><button className="danger-button" disabled={busy} onClick={async()=>{setBusy(true);try{await onConfirm();onClose();}catch(err){setError(err instanceof Error?err.message:'Could not complete this action.');}finally{setBusy(false);}}}>{busy?'Working...':'Confirm'}</button></div></section></div>; }
export function exportCsv(filename:string, rows:Record<string,unknown>[]) { if(!rows.length)return; const headers=Object.keys(rows[0]); const cell=(value:unknown)=>{let text=String(value??'');if(/^[=+\-@]/.test(text))text=`'${text}`;return `"${text.replace(/"/g,'""')}"`;};const blob=new Blob(['\uFEFF'+[headers.map(cell).join(','),...rows.map((row)=>headers.map((header)=>cell(row[header])).join(','))].join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url); }
