import { useState } from 'react';
import { CalendarCheck, Users, Wallet, Download, Pencil } from 'lucide-react';
import { useWorkspace } from '../context/WorkspaceContext';
import { Badge, Card, EmptyState, PageIntro, RecordForm, StatCard, WorkspaceStatus, exportCsv } from '../components/WorkspaceUI';
import { dateInput, refId, type WorkerRecord } from '../types/workspace';
import { earnedWage, monthlyPayroll } from '../utils/payroll';
import { formatCurrency } from '../utils/format';

export function AttendancePage() {
  const { data,role,loading,error,save,siteName,workerName }=useWorkspace();const [date,setDate]=useState(dateInput);const [site,setSite]=useState('');const [worker,setWorker]=useState<WorkerRecord|null>(null);
  const history=data.attendance.filter((entry)=>!site||refId(entry.site)===site);const entries=data.attendance.filter((entry)=>entry.date.slice(0,10)===date&&(!site||refId(entry.site)===site));const workers=data.workers.filter((entry)=>!site||refId(entry.assignedSite)===site);const present=workers.filter((entry)=>entries.find((record)=>refId(record.worker)===entry._id)?.status==='Present').length;
  const liability=workers.reduce((sum,entry)=>{const record=entries.find((record)=>refId(record.worker)===entry._id);return sum+(record?earnedWage(record,entry.dailyWage):0);},0);
  if(loading||error)return <WorkspaceStatus/>;
  return <div className="page-enter"><PageIntro eyebrow={role==='worker'?'My shift records':'Daily muster'} title={role==='worker'?'My attendance':'Labour & attendance'} description={role==='worker'?'Review your verified attendance. Contact your site manager if a record needs correction.':'Mark daily attendance for your site workforce. Re-marking a day updates the existing record.'} actions={<button className="secondary-button" disabled={role==='worker'?!history.length:!entries.length} onClick={()=>exportCsv(`muster-${role==='worker'?'history':date}.csv`,(role==='worker'?history:entries).map((entry)=>({Worker:workerName(entry.worker),Site:siteName(entry.site),Date:entry.date.slice(0,10),Attendance:entry.status,Shift:entry.shift||'General',Notes:entry.notes||''})))}><Download size={16}/>Export muster</button>}/>
    {role!=='worker'&&<div className="mb-6 grid gap-4 sm:grid-cols-3"><StatCard label="Roster for selected sites" value={workers.length} detail="Registered workforce" icon={Users}/><StatCard label="Present on selected day" value={present} detail={`${entries.filter((entry)=>entry.status==='Half Day').length} half days recorded`} icon={CalendarCheck} tone="green"/><StatCard label="Daily wage liability" value={formatCurrency(liability)} detail="Present + half day wages" icon={Wallet} tone="blue"/></div>}
    <div className="mb-5 flex flex-wrap items-center gap-3">{role!=='worker'&&<label className="flex items-center gap-2 text-xs text-ink-500">Muster date<input aria-label="Muster date" className="filter-select" type="date" value={date} onChange={(event)=>setDate(event.target.value)}/></label>}<select aria-label="Filter by site" className="filter-select" value={site} onChange={(event)=>setSite(event.target.value)}><option value="">All assigned sites</option>{data.sites.map((entry)=><option key={entry._id} value={entry._id}>{entry.siteName}</option>)}</select></div>
    <Card title={role==='worker'?'Shift history':'Worker muster'} subtitle={role==='worker'?'All recorded dates':'Select a worker to mark or correct attendance'}>{role==='worker'?<div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Site</th><th>Shift</th><th>Attendance</th><th>Remarks</th></tr></thead><tbody>{history.slice().sort((a,b)=>b.date.localeCompare(a.date)).map((entry)=><tr key={entry._id}><td>{entry.date.slice(0,10)}</td><td>{siteName(entry.site)}</td><td>{entry.shift||'General'}</td><td><Badge>{entry.status}</Badge></td><td>{entry.notes||'—'}</td></tr>)}</tbody></table>{!history.length&&<EmptyState title="No attendance records yet" detail="Your manager records your attendance. Verified shifts will appear here."/>}</div>:workers.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Worker</th><th>Trade</th><th>Site</th><th>Daily wage</th><th>Attendance</th><th>Action</th></tr></thead><tbody>{workers.map((entry)=>{const record=entries.find((item)=>refId(item.worker)===entry._id);return <tr key={entry._id}><td><p className="font-medium text-ink-900">{entry.fullName}</p><p className="mt-1 text-[11px] text-ink-400">{entry.phone}</p></td><td>{entry.skill}</td><td>{siteName(entry.assignedSite)}</td><td className="font-mono">{formatCurrency(entry.dailyWage)}</td><td>{record?<Badge>{record.status}</Badge>:<span className="text-xs text-ink-400">Not marked</span>}</td><td><button className="secondary-button text-xs" disabled={!refId(entry.assignedSite)||(entry.status!=='Active'&&!record)} onClick={()=>setWorker(entry)}><Pencil size={13}/>{record?'Correct':'Mark'}</button></td></tr>;})}</tbody></table></div>:<EmptyState title="No workers on this site" detail="Register workers and assign them to a site in the Workforce module."/>}</Card>
    {worker&&<RecordForm title={`Attendance · ${worker.fullName}`} description={`${siteName(worker.assignedSite)} · ${date}`} initial={{date,status:entries.find((entry)=>refId(entry.worker)===worker._id)?.status||'Present',shift:entries.find((entry)=>refId(entry.worker)===worker._id)?.shift||'General',notes:entries.find((entry)=>refId(entry.worker)===worker._id)?.notes||''}} fields={[{key:'date',label:'Muster date',type:'date',required:true},{key:'status',label:'Attendance',required:true,options:['Present','Half Day','Absent'].map((value)=>({value,label:value}))},{key:'shift',label:'Shift',required:true,options:['Morning','General','Night'].map((value)=>({value,label:value}))},{key:'notes',label:'Remarks',type:'textarea'}]} onClose={()=>setWorker(null)} onSave={(values)=>save('attendance',{...values,worker:worker._id,site:refId(worker.assignedSite)})}/>}
  </div>;
}
export function WagesPage() {
  const { data,role,loading,error,siteName }=useWorkspace();const [month,setMonth]=useState(()=>dateInput().slice(0,7));const [site,setSite]=useState('');
  const rows=data.workers.filter((worker)=>!site||refId(worker.assignedSite)===site).map((worker)=>{const records=data.attendance.filter((entry)=>refId(entry.worker)===worker._id&&entry.date.slice(0,7)===month);return {worker,...monthlyPayroll(worker,records)};});
  if(loading||error)return <WorkspaceStatus/>;
  return <div className="page-enter"><PageIntro eyebrow="Payroll register" title={role==='worker'?'My wages':'Wages & payroll'} description="Monthly earned wages calculated from the wage rate stored with each verified shift. Payment disbursements are recorded separately in Expenses." actions={<button className="secondary-button" disabled={!rows.length} onClick={()=>exportCsv(`wages-${month}.csv`,rows.map((row)=>({Worker:row.worker.fullName,Site:siteName(row.worker.assignedSite),Month:month,DailyRate:row.worker.dailyWage,PresentDays:row.present,HalfDays:row.half,AbsentDays:row.absent,EarnedWages:row.amount})))}><Download size={16}/>Export payroll</button>}/><div className="mb-6 grid gap-4 sm:grid-cols-3"><StatCard label="Earned wages" value={formatCurrency(rows.reduce((sum,row)=>sum+row.amount,0))} detail={`Selected month: ${month}`} icon={Wallet} tone="blue"/><StatCard label="Recorded present days" value={rows.reduce((sum,row)=>sum+row.present,0)} detail="Full attendance days" icon={CalendarCheck} tone="green"/><StatCard label="Workers in register" value={rows.length} detail="Within your assigned workspace" icon={Users}/></div><div className="mb-5 flex flex-wrap gap-3"><input aria-label="Payroll month" type="month" className="filter-select" value={month} onChange={(event)=>setMonth(event.target.value)}/><select aria-label="Filter by site" className="filter-select" value={site} onChange={(event)=>setSite(event.target.value)}><option value="">All assigned sites</option>{data.sites.map((entry)=><option key={entry._id} value={entry._id}>{entry.siteName}</option>)}</select></div><p className="mb-4 text-xs leading-5 text-ink-500">{rows.reduce((sum,row)=>sum+row.legacyRateDays,0)>0?`${rows.reduce((sum,row)=>sum+row.legacyRateDays,0)} historical shifts have no stored rate and use the worker’s current daily rate. Review these before settlement.`:'Rates are preserved with attendance records. Payment entries are tracked in Expenses.'}</p><Card>{rows.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Worker</th><th>Site</th><th>Daily rate</th><th>Present days</th><th>Half days</th><th>Absent days</th><th>Earned wages</th></tr></thead><tbody>{rows.map((row)=><tr key={row.worker._id}><td className="font-medium text-ink-900">{row.worker.fullName}</td><td>{siteName(row.worker.assignedSite)}</td><td>{formatCurrency(row.worker.dailyWage)}</td><td>{row.present}</td><td>{row.half}</td><td>{row.absent}</td><td className="font-mono font-semibold text-ink-900">{formatCurrency(row.amount)}</td></tr>)}</tbody></table></div>:<EmptyState title="No payroll records" detail="A registered worker and verified attendance are needed to calculate wages."/>}</Card></div>;
}
