import { useEffect, useState, type FormEvent } from 'react';
import { Link, Navigate, useNavigate, useLocation } from 'react-router-dom';
import { HardHat, ShieldCheck, ArrowRight, Loader2, CheckCircle2 } from 'lucide-react';
import { useAuth, type User } from '../context/AuthContext';
import { apiRequest } from '../services/api';

export function LoginPage() {
  const {login,isAuthenticated}=useAuth();const location=useLocation();const navigate=useNavigate();const [register,setRegister]=useState(false);const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [registrationEnabled,setRegistrationEnabled]=useState(false);
  useEffect(()=>{let active=true;void apiRequest<{registrationEnabled:boolean}>('/auth/config').then(config=>{if(active)setRegistrationEnabled(config.registrationEnabled);}).catch(()=>{if(active)setRegistrationEnabled(false);});return()=>{active=false;};},[]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const response=await apiRequest<{token:string;user:User}>(register?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify(register?{name,email,password,role:'owner'}:{email,password})});login(response.token,response.user);navigate('/');}catch(err){setError(err instanceof Error?err.message:'Could not sign you in.');}finally{setBusy(false);}};
  if(isAuthenticated)return <Navigate to="/" replace/>;
  return <div className="login-page"><section className="login-story"><Link to="/login" className="flex items-center gap-3"><span className="rounded-xl bg-safety-400 p-2.5 text-ink-900"><HardHat size={26}/></span><span className="text-2xl font-semibold tracking-tight">maple<span className="text-safety-400">.</span></span></Link><div className="relative z-10 my-auto py-14"><p className="mb-6 text-[11px] font-semibold uppercase tracking-[.24em] text-safety-300">BUILT FOR THE WAY YOU BUILD</p><h1 className="max-w-lg text-4xl font-semibold leading-[1.2] tracking-tight xl:text-5xl">Great projects start<br/>with a connected<br/><span className="text-safety-300">site team.</span></h1><p className="mt-6 max-w-sm text-sm leading-7 text-white/55">From the boardroom to the building site. Bring your people, projects and daily operations into one workspace.</p><div className="mt-9 space-y-3">{['A dedicated workspace for every role','Clear visibility across every site','Daily operations that move work forward'].map((text)=><p key={text} className="flex items-center gap-2.5 text-xs text-white/70"><CheckCircle2 size={16} className="text-safety-300"/>{text}</p>)}</div></div><div className="construction-line-art" aria-hidden="true"><span/><span/><span/><span/></div><p className="relative z-10 text-[10px] text-white/30">MAPLE CONSTRUCTION / SITE OPERATIONS PLATFORM</p></section>
    <section className="login-form-side"><div className="w-full max-w-[410px]"><div className="mb-9"><p className="mb-3 text-[11px] font-semibold uppercase tracking-[.15em] text-safety-600">YOUR SITE WORKSPACE</p><h2 className="text-3xl font-semibold tracking-tight">{register?'Create your workspace':'Welcome back'}</h2><p className="mt-3 text-sm leading-6 text-ink-500">{register?'Start as the owner, then invite managers and workers from Team access.':'Sign in to continue to your role’s dashboard.'}</p></div>
      {location.state?.message&&<p role="status" className="mb-5 rounded-xl bg-signal-greenSoft p-3 text-sm text-signal-green">{String(location.state.message)}</p>}{error&&<p role="alert" className="mb-5 rounded-xl border border-red-100 bg-signal-redSoft p-3 text-xs leading-5 text-signal-red">{error}</p>}
      <form onSubmit={submit} className="space-y-5">{register&&<label className="field-label">Full name<input className="field-input" autoComplete="name" required value={name} onChange={(event)=>setName(event.target.value)} placeholder="Your name"/></label>}<label className="field-label">Email address<input className="field-input" type="email" required autoComplete="email" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="you@company.com"/></label><label className="field-label">Password<input className="field-input" type="password" required minLength={register?8:undefined} autoComplete={register?'new-password':'current-password'} value={password} onChange={(event)=>setPassword(event.target.value)} placeholder={register?'At least 8 characters':'Enter your password'}/></label><button className="primary-button w-full justify-center py-3" disabled={busy} type="submit">{busy?<Loader2 className="animate-spin" size={17}/>:null}{busy?'Please wait...':register?'Create owner workspace':'Sign in'}<ArrowRight size={16}/></button></form>
      {registrationEnabled&&<p className="mt-5 text-center text-xs text-ink-500">{register?'Already have an account?':'New to Maple?'} <button type="button" className="font-semibold text-steel-600" onClick={()=>{setRegister(!register);setError('');}}>{register?'Sign in':'Create a workspace'}</button></p>}
      <p className="mt-8 flex items-center justify-center gap-2 text-xs leading-5 text-ink-400"><ShieldCheck size={15}/>Secure access for your construction team.</p><p className="mt-3 text-center text-xs leading-5 text-ink-400">Managers and workers: contact your workspace owner for an account or password assistance.</p>
    </div></section>
  </div>;
}
export default LoginPage;
