import React from "react";
import { FileTextIcon, ClipboardListIcon, PackageIcon, HardHatIcon, WalletIcon, ShieldCheckIcon, DownloadIcon, ClockIcon, BoxIcon } from "lucide-react";
import { PageHeader } from "../components/ui/PageHeader";
import { Button } from "../components/ui/Button";
import { Panel, PanelHeader } from "../components/ui/Panel";
import { StatusBadge } from "../components/ui/StatusBadge";
import { TableWrap, Th, Td, Tr } from "../components/ui/Table";
interface ReportType {
  name: string;
  description: string;
  icon: BoxIcon;
  cadence: string;
}
const reportTypes: ReportType[] = [{
  name: 'Daily Progress Report (DPR)',
  description: 'Activity-wise progress, manpower, plant deployed and weather log.',
  icon: ClipboardListIcon,
  cadence: 'Daily · 7:00 PM cut-off'
}, {
  name: 'Monthly Progress Report',
  description: 'Planned vs actual S-curve, billing status, key risks and photographs.',
  icon: FileTextIcon,
  cadence: 'Monthly · 5th'
}, {
  name: 'Material Reconciliation',
  description: 'Receipts, consumption, wastage and closing stock against theoretical draw.',
  icon: PackageIcon,
  cadence: 'Weekly · Monday'
}, {
  name: 'Labour & Wage Register',
  description: 'Muster roll, contractor-wise deployment and statutory compliance.',
  icon: HardHatIcon,
  cadence: 'Fortnightly'
}, {
  name: 'Cost & Cash Flow',
  description: 'Committed cost, incurred cost, cash out and projections to completion.',
  icon: WalletIcon,
  cadence: 'Monthly · 3rd'
}, {
  name: 'Safety & Quality Audit',
  description: 'HSE observations, NCRs, cube test summary and closure status.',
  icon: ShieldCheckIcon,
  cadence: 'Weekly · Saturday'
}];
const generated = [{
  id: 'r1',
  name: 'DPR — 17 Aug 2026',
  project: 'PRJ-2041',
  by: 'A. Kulkarni',
  on: '17 Aug 2026, 6:48 PM',
  status: 'Approved'
}, {
  id: 'r2',
  name: 'Material Reconciliation — Week 33',
  project: 'PRJ-2038',
  by: 'T. Gawde',
  on: '17 Aug 2026, 11:20 AM',
  status: 'For Review'
}, {
  id: 'r3',
  name: 'Monthly Progress Report — Jul 2026',
  project: 'PRJ-2029',
  by: 'R. Deshmukh',
  on: '05 Aug 2026, 4:12 PM',
  status: 'Approved'
}, {
  id: 'r4',
  name: 'Safety & Quality Audit — Week 32',
  project: 'PRJ-2041',
  by: 'N. Bhosale',
  on: '02 Aug 2026, 5:35 PM',
  status: 'Approved'
}];
export function Reports() {
  return <div className="mx-auto w-full max-w-[1600px]">
      <PageHeader eyebrow="Reporting" title="Reports" description="Generate contractual and internal reports from live site data." actions={<Button variant="primary" size="md">
            Generate report
          </Button>} />

      <Panel className="mb-4 border-l-2 border-l-safety-400 p-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-start gap-3">
            <ClockIcon className="mt-0.5 h-4 w-4 shrink-0 text-safety-500" aria-hidden />
            <div>
              <p className="text-sm font-semibold text-ink-900">
                3 daily progress reports pending for 18 Aug
              </p>
              <p className="mt-0.5 text-xs text-ink-500">
                Ring Road Flyover, Aurum Residency and Warehouse Unit 4 have not submitted today's DPR.
              </p>
            </div>
          </div>
          <Button variant="secondary" size="sm">
            Send reminder
          </Button>
        </div>
      </Panel>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
        {reportTypes.map((r) => <Panel key={r.name} className="p-4" as="article">
            <div className="flex items-start gap-3">
              <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-ink-100">
                <r.icon className="h-4 w-4 text-ink-700" aria-hidden />
              </span>
              <div className="min-w-0">
                <h2 className="text-sm font-semibold leading-snug text-ink-900">{r.name}</h2>
                <p className="mt-1 text-xs leading-snug text-ink-500">{r.description}</p>
              </div>
            </div>
            <div className="mt-4 flex items-center justify-between border-t border-ink-100 pt-3">
              <span className="font-mono text-2xs text-ink-400">{r.cadence}</span>
              <Button variant="secondary" size="sm">
                <DownloadIcon className="h-3.5 w-3.5" aria-hidden />
                Generate
              </Button>
            </div>
          </Panel>)}
      </div>

      <Panel className="mt-4 overflow-hidden">
        <PanelHeader title="Recently generated" subtitle="Shared with client and internal stakeholders" />
        <TableWrap>
          <thead>
            <tr>
              <Th>Report</Th>
              <Th>Project</Th>
              <Th>Generated by</Th>
              <Th>Generated on</Th>
              <Th>Status</Th>
              <Th align="right" />
            </tr>
          </thead>
          <tbody>
            {generated.map((g) => <Tr key={g.id}>
                <Td className="text-xs font-semibold text-ink-900">{g.name}</Td>
                <Td className="font-mono text-2xs text-ink-500">{g.project}</Td>
                <Td className="text-xs">{g.by}</Td>
                <Td className="font-mono text-2xs text-ink-600">{g.on}</Td>
                <Td>
                  <StatusBadge label={g.status} />
                </Td>
                <Td align="right">
                  <Button variant="ghost" size="sm">
                    <DownloadIcon className="h-3.5 w-3.5" aria-hidden />
                    PDF
                  </Button>
                </Td>
              </Tr>)}
          </tbody>
        </TableWrap>
      </Panel>
    </div>;
}