import { useState, useEffect, type ReactNode } from 'react';
import { Plus, Search, Download, Pencil, Trash2, ArrowUpRight, Building2, MapPin, CalendarDays, Package, ClipboardList, Users, FileText, ShieldAlert, Receipt, FolderOpen, LayoutGrid, List, Loader2 } from 'lucide-react';
import { useWorkspace } from '../context/WorkspaceContext';
import { apiRequest } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { Card, Badge, EmptyState, PageIntro, RecordForm, ConfirmDialog, WorkspaceStatus, exportCsv, type Field } from '../components/WorkspaceUI';
import { dateInput, refId, type Resource, type Relation } from '../types/workspace';
import { formatCurrency } from '../utils/format';

interface Column { label:string; render:(record: Record<string,unknown>)=>ReactNode }
interface Definition { title:string; subtitle:string; singular:string; icon:typeof Building2; fields:Field[]; columns:string[]; statuses?:string[] }
const options = (values:string[]) => values.map((value)=>({value,label:value}));
const field = (key:string,label:string,type='text',required=true):Field => ({key,label,type,required,...(type==='number'?{min:0}: {})});
const select = (key:string,label:string,values:string[],required=true):Field => ({key,label,options:options(values),required});
export const definitions: Record<Resource,Definition> = {
  sites:{title:'Projects & sites',subtitle:'A clear view of your construction portfolio, timelines and execution progress.',singular:'site',icon:Building2,fields:[field('siteName','Site name'),field('location','Location'),field('clientName','Client name'),field('managerName','Site manager','text',false),field('budget','Contract budget (₹)','number'),{...field('progress','Progress (%)','number'),max:100},field('startDate','Start date','date'),field('expectedEndDate','Target completion','date'),select('status','Status',['Planning','Ongoing','Completed'])],columns:['siteName','location','progress','status'],statuses:['Planning','Ongoing','Completed']},
  workers:{title:'Workforce register',subtitle:'Register workers, assign a site and maintain the roster for daily operations.',singular:'worker',icon:Users,fields:[field('fullName','Full name'),field('phone','Phone number','tel'),field('email','Email address','email',false),select('skill','Trade',['Mason','Electrician','Plumber','Painter','Carpenter','Labour','Supervisor','Other']),field('dailyWage','Daily wage (₹)','number'),field('assignedSite','Assigned site'),select('status','Status',['Active','Inactive']),field('emergencyContact','Emergency contact','tel',false)],columns:['fullName','skill','assignedSite','phone','dailyWage','status'],statuses:['Active','Inactive']},
  contractors:{title:'Contractors',subtitle:'Manage site partners, trade teams and their contact information.',singular:'contractor',icon:Users,fields:[field('companyName','Company name'),field('contactName','Contact person'),field('phone','Phone number','tel'),field('email','Email address','email',false),field('trade','Trade / scope'),field('site','Site'),field('crewSize','Crew size','number'),select('status','Status',['Active','On hold','Completed'])],columns:['companyName','contactName','phone','trade','site','crewSize','status'],statuses:['Active','On hold','Completed']},
  tasks:{title:'Task board',subtitle:'Plan work, assign the right crew and keep every work package moving.',singular:'task',icon:ClipboardList,fields:[field('title','Task title'),field('site','Site'),field('assignedTo','Assigned worker','text',false),select('priority','Priority',['Low','Medium','High','Critical']),field('dueDate','Due date','date'),select('status','Status',['Pending','In Progress','Blocked','Completed']),field('description','Work instructions','textarea',false)],columns:['title','site','assignedTo','priority','dueDate','status'],statuses:['Pending','In Progress','Blocked','Completed']},
  materials:{title:'Materials & inventory',subtitle:'Know what is on site, what needs replenishing and the value of your stock.',singular:'material',icon:Package,fields:[field('materialName','Material name'),select('category','Category',['Cement','Steel','Bricks','Sand','Gravel','Paint','Electrical','Plumbing','Other']),field('site','Site'),field('quantity','Available quantity','number'),select('unit','Unit',['Kg','Ton','Bag','Piece','Litre','Cubic Meter']),field('costPerUnit','Unit cost (₹)','number'),field('reorderLevel','Reorder threshold','number'),field('supplier','Supplier','text',false)],columns:['materialName','category','site','quantity','valuation','stock']},
  expenses:{title:'Expenses & approvals',subtitle:'Record site expenditure, review pending vouchers and track payments.',singular:'expense',icon:Receipt,fields:[field('description','Expense description'),field('site','Site'),select('category','Category',['Material','Labour','Transport','Equipment','Maintenance','Miscellaneous']),field('amount','Amount (₹)','number'),field('expenseDate','Expense date','date'),select('status','Approval status',['Pending','Approved','Rejected','Paid']),field('paidTo','Payee / vendor'),select('paymentMethod','Payment method',['Bank transfer','UPI','Cash','Cheque'],false)],columns:['description','site','category','expenseDate','paidTo','amount','status'],statuses:['Pending','Approved','Rejected','Paid']},
  attendance:{title:'Attendance',subtitle:'Daily worker muster and verified shift records.',singular:'attendance',icon:CalendarDays,fields:[field('worker','Worker'),field('site','Site'),field('date','Muster date','date'),select('status','Attendance',['Present','Half Day','Absent']),select('shift','Shift',['Morning','General','Night']),field('notes','Remarks','textarea',false)],columns:['worker','site','date','shift','status']},
  issues:{title:'Issues & safety',subtitle:'Report hazards and quality defects, then track them through to resolution.',singular:'issue',icon:ShieldAlert,fields:[field('title','Issue title'),field('site','Site'),select('category','Category',['Safety','Quality','Equipment','Other']),select('severity','Severity',['Low','Medium','High','Critical']),select('status','Status',['Open','In Review','Resolved','Closed']),field('description','What happened?','textarea')],columns:['title','site','category','severity','status'],statuses:['Open','In Review','Resolved','Closed']},
  reports:{title:'Daily reports',subtitle:'Capture daily progress, site conditions and safety observations in one place.',singular:'report',icon:FileText,fields:[field('title','Report title'),field('site','Site'),select('type','Report type',['Daily progress','Safety inspection']),field('date','Report date','date'),field('weather','Weather / site conditions','text',false),{...field('hoursWorked','Hours worked','number',false),max:24},field('summary','Progress / safety observations','textarea')],columns:['title','site','type','date','summary']},
  documents:{title:'Document library',subtitle:'Keep drawings, permits and reference documents available to site teams.',singular:'document',icon:FolderOpen,fields:[field('title','Document title'),field('site','Site'),select('type','Document type',['Drawing','Contract','Permit','Report','Certificate']),field('revision','Revision'),field('url','Document link','url',false),{...field('attachment','Upload a file','file',false),hint:'PDF, PNG or JPEG, up to 2 MB. Provide a link or upload a file.'}],columns:['title','site','type','revision','url']},
  team:{title:'Team access',subtitle:'Give managers access to their sites and link worker logins to workforce records.',singular:'account',icon:Users,fields:[field('name','Full name'),field('email','Email address','email'),field('password','Temporary password','password'),select('role','Access role',['hr','worker']),field('assignedSites','Manager sites'),field('workerId','Linked worker','text',false)],columns:['name','email','role','assignedSites','active']},
};
const labels:Record<string,string>={companyName:'Company',contactName:'Contact',crewSize:'Crew size',siteName:'Project',fullName:'Worker',materialName:'Material',title:'Details',description:'Description',site:'Site',assignedSite:'Site',assignedTo:'Assigned to',skill:'Trade',dailyWage:'Daily wage',dueDate:'Due date',expenseDate:'Date',paidTo:'Payee',amount:'Amount',valuation:'Stock value',stock:'Stock status',costPerUnit:'Unit rate',quantity:'Quantity',worker:'Worker',url:'File',assignedSites:'Assigned sites',active:'Account status',name:'Team member',email:'Email',date:'Date',summary:'Summary',progress:'Progress'};

export function ResourcePage({ resource }: {resource:Resource}) {
  const { data,role,loading,error,save,remove,refresh,siteName,workerName }=useWorkspace(); const { user }=useAuth(); const def=definitions[resource];
  const [search,setSearch]=useState(''); const [siteFilter,setSiteFilter]=useState(''); const [statusFilter,setStatusFilter]=useState(''); const [layout,setLayout]=useState<'board'|'table'>(resource==='tasks'?'board':'table');
  const [form,setForm]=useState<Record<string,unknown>|null>(null); const [editingId,setEditingId]=useState<string|undefined>(); const [deleteId,setDeleteId]=useState<string>();const [resetPasswordId,setResetPasswordId]=useState<string>(); const [actionError,setActionError]=useState('');const [busyId,setBusyId]=useState('');const [page,setPage]=useState(1);const [sort,setSort]=useState({key:def.columns[0],descending:false});
  useEffect(()=>setPage(1),[search,siteFilter,statusFilter,layout]);
  const canCreate = role==='owner'||role==='hr'&& !['sites','expenses','team'].includes(resource)||role==='worker'&&['issues','reports'].includes(resource);
  const canEdit = role!=='worker'; const canDelete=role==='owner'||role==='hr'&&!['sites','team','expenses'].includes(resource);
  const records=data[resource] as unknown as Record<string,unknown>[];
  const shown=records.filter((record)=>{
    const content=[...Object.values(record).filter((value)=>typeof value==='string'||typeof value==='number'),siteName(record.site as Relation),workerName(record.assignedTo as Relation)].join(' ').toLowerCase();
    return content.includes(search.toLowerCase())&&(!siteFilter||refId((record.site||record.assignedSite)as Relation)===siteFilter)&&(!statusFilter||record.status===statusFilter);
  });
  const defaultValues:Record<string,unknown>={status:def.statuses?.[0],site:data.sites.length===1?data.sites[0]._id:'',assignedSite:'',progress:0,budget:0,crewSize:0,date:dateInput(),expenseDate:dateInput(),startDate:dateInput(),expectedEndDate:dateInput(),dueDate:dateInput(),priority:'Medium',severity:'Medium',category:resource==='issues'?'Safety':resource==='materials'?'Cement':'Material',type:resource==='reports'?(role==='worker'?'Safety inspection':'Daily progress'):'Drawing',revision:'R0',active:true,role:'hr',reorderLevel:10,statusOverride:'',shift:'General',hoursWorked:8};
  if(resource==='workers')defaultValues.status='Active'; if(resource==='issues')defaultValues.status='Open'; if(resource==='reports'&&role==='worker')defaultValues.hoursWorked=0;
  const openForm=(record?:Record<string,unknown>)=>{setEditingId(record?._id as string|undefined);setForm(record?{...record,site:refId(record.site as Relation),assignedSite:refId(record.assignedSite as Relation),assignedTo:refId(record.assignedTo as Relation),worker:refId(record.worker as Relation),startDate:String(record.startDate||'').slice(0,10),expectedEndDate:String(record.expectedEndDate||'').slice(0,10),dueDate:String(record.dueDate||'').slice(0,10),expenseDate:String(record.expenseDate||'').slice(0,10),date:String(record.date||'').slice(0,10)}:defaultValues);};
  const fields=def.fields.filter((entry)=>!(resource==='sites'&&role==='hr'&&!['progress','status'].includes(entry.key))&& !(role==='worker'&&resource==='issues'&&entry.key==='status') && !(editingId&&resource==='team'&&['password','role','workerId'].includes(entry.key))).map((entry):Field=>{
    if(['site','assignedSite'].includes(entry.key))return {...entry,required:entry.key==='site'||role==='hr',options:data.sites.map((site)=>({value:site._id,label:site.siteName}))};
    if(['assignedTo','worker','workerId'].includes(entry.key))return {...entry,filterBy:['assignedTo','worker'].includes(entry.key)?'site':undefined,when:entry.key==='workerId'?{key:'role',value:'worker'}:undefined,options:data.workers.filter((worker)=>worker.status==='Active'&&(entry.key!=='workerId'||!worker.userId)).map((worker)=>({value:worker._id,label:`${worker.fullName} · ${siteName(worker.assignedSite)}`,scopeId:refId(worker.assignedSite)})),hint:entry.key==='workerId'?'Required when creating a field worker account.':'Choose a worker assigned to the selected site.'};
    if(entry.key==='assignedSites')return {...entry,type:'multiselect',required:true,when:{key:'role',value:'hr'},options:data.sites.map((site)=>({value:site._id,label:site.siteName})),hint:'Select one or more sites for a manager.'};
    if(entry.key==='role')return {...entry,options:[{value:'hr',label:'Site HR / Manager'},{value:'worker',label:'Field Worker'}]};
    if(resource==='reports'&&role==='worker'&&entry.key==='type')return {...entry,options:options(['Safety inspection'])};return entry;
  });
  const changeStatus=async(record:Record<string,unknown>,status:string)=>{setBusyId(String(record._id));setActionError('');try{await save(resource,{status},String(record._id));}catch(err){setActionError(err instanceof Error?err.message:'Could not update the status.');}finally{setBusyId('');}};
  const renderValue=(record:Record<string,unknown>,key:string):ReactNode=>{
    const value=record[key];if(['site','assignedSite'].includes(key))return siteName(value as Relation);if(['worker','assignedTo'].includes(key))return workerName(value as Relation);
    if(['status','priority','severity'].includes(key))return <Badge>{String(value||'Pending')}</Badge>;
    if(key==='active')return <Badge>{value===false?'Inactive':'Active'}</Badge>;
    if(key==='assignedSites')return <span className="text-xs">{((value||[])as string[]).map((id)=>siteName(id)).join(', ')||'Worker profile assignment'}</span>;
    if(['budget','dailyWage','amount','costPerUnit'].includes(key))return <span className="font-mono">{formatCurrency(Number(value||0))}</span>;
    if(['startDate','expectedEndDate','expenseDate','date','dueDate'].includes(key))return value?new Date(String(value)).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kolkata'}):'—';
    if(key==='valuation')return <span className="font-mono">{formatCurrency(Number(record.quantity)*Number(record.costPerUnit))}</span>;
    if(key==='quantity')return <span className="font-mono">{String(value)} <span className="text-ink-400">{String(record.unit)}</span></span>;
    if(key==='stock')return <Badge>{Number(record.quantity)<=Number(record.reorderLevel)?'Low stock':'Healthy'}</Badge>;
    if(key==='progress')return <div className="min-w-[100px]"><span className="text-xs font-semibold">{Number(value||0)}%</span><div className="mt-1 h-1.5 rounded-full bg-ink-100"><div className="h-full rounded-full bg-safety-400" style={{width:`${Number(value||0)}%`}}/></div></div>;
    if(key==='url')return record.hasAttachment||record.attachment?<button className="text-xs font-semibold text-steel-600" disabled={busyId===record._id} onClick={async()=>{setBusyId(String(record._id));setActionError('');try{const saved=await apiRequest<{attachment?:string;fileName?:string}>(`/documents/${record._id}`);if(!saved.attachment)throw new Error('This document has no downloadable attachment.');const parts=saved.attachment.match(/^data:([^;]+);base64,(.+)$/);if(!parts)throw new Error('This attachment could not be read.');const bytes=Uint8Array.from(atob(parts[2]),(character)=>character.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:parts[1]}));const link=document.createElement('a');link.href=url;link.download=saved.fileName||String(record.title);link.click();URL.revokeObjectURL(url);}catch(err){setActionError(err instanceof Error?err.message:'Could not download this document.');}finally{setBusyId('');}}}>{busyId===record._id?'Downloading…':'Download'}</button>:typeof value==='string'&&/^https?:\/\//i.test(value)?<a href={value} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs font-semibold text-steel-600">Open<ArrowUpRight size={14}/></a>:'—';
    if(key==='title'&&record.description)return <div className="max-w-sm"><p className="font-medium text-ink-900">{String(value)}</p><p className="mt-1 text-xs leading-5 text-ink-500">{String(record.description)}</p></div>;
    if(key==='role')return record.role==='owner'?'Owner / Director':record.role==='hr'?'Site HR / Manager':'Field Worker';
    if(key==='summary')return <span className="line-clamp-2 max-w-md text-xs leading-5 text-ink-500">{String(value||'')}</span>;
    return <span className={['title','fullName','materialName','description','name'].includes(key)?'font-medium text-ink-900':''}>{String(value??'—')}</span>;
  };
  const sorted=[...shown].sort((a,b)=>{const key=sort.key;const value=(record:Record<string,unknown>)=>['site','assignedSite'].includes(key)?siteName(record[key]as Relation):key==='assignedTo'?workerName(record[key]as Relation):key==='valuation'?Number(record.quantity)*Number(record.costPerUnit):record[key]??'';const left=value(a),right=value(b);const comparison=typeof left==='number'&&typeof right==='number'?left-right:String(left).localeCompare(String(right),'en-IN',{numeric:true});return sort.descending?-comparison:comparison;});
  const pageSize=resource==='sites'?6:20;const pages=Math.max(1,Math.ceil(sorted.length/pageSize));const currentPage=Math.min(page,pages);const pageItems=sorted.slice((currentPage-1)*pageSize,currentPage*pageSize);
  const columns:Column[]=def.columns.map((key)=>({label:labels[key]||key[0].toUpperCase()+key.slice(1),render:(record)=>renderValue(record,key)}));
  if(loading||error)return <WorkspaceStatus/>;
  const allowNew=canCreate&&(resource==='sites'||data.sites.length>0);
  return <div className="page-enter"><PageIntro eyebrow={role==='worker'?'My workspace':'Site operations'} title={role==='worker'&&resource==='tasks'?'My work queue':role==='worker'&&resource==='issues'?'My issues & safety reports':def.title} description={def.subtitle} actions={<><button className="secondary-button" disabled={!shown.length} onClick={()=>exportCsv(`maple-${resource}.csv`,shown.map((record)=>Object.fromEntries(def.columns.map((key)=>[labels[key]||key,['site','assignedSite'].includes(key)?siteName(record[key]as Relation):['worker','assignedTo'].includes(key)?workerName(record[key]as Relation):key==='assignedSites'?((record[key]||[])as string[]).map((site)=>siteName(site)).join('; '):record[key]]))))}><Download size={16}/>Export</button>{canCreate&&<button className="primary-button" disabled={!allowNew} onClick={()=>openForm()}><Plus size={16}/>{resource==='team'?'Create account':resource==='reports'?'Submit report':`Add ${def.singular}`}</button>}</>}/>
    {!data.sites.length&&resource!=='sites'&&<p className="mb-5 rounded-xl border border-ink-200 bg-white p-4 text-sm leading-6 text-ink-500">{role==='owner'?'Create a site in Projects & sites before adding site records or team accounts.':'Your workspace owner needs to assign a site before you can add site records.'}</p>}{actionError&&<p role="alert" className="mb-4 rounded-lg bg-signal-redSoft p-3 text-sm text-signal-red">{actionError}</p>}
    <div className="mb-5 flex flex-wrap items-center gap-3"><div className="relative w-full max-w-sm"><Search size={16} className="absolute left-3 top-3 text-ink-400"/><input aria-label={`Search ${def.title}`} className="field-input pl-10" placeholder={`Search ${resource}...`} value={search} onChange={(event)=>setSearch(event.target.value)}/></div>{!['sites','team'].includes(resource)&&<select aria-label="Filter by site" className="filter-select" value={siteFilter} onChange={(event)=>setSiteFilter(event.target.value)}><option value="">All assigned sites</option>{data.sites.map((site)=><option key={site._id} value={site._id}>{site.siteName}</option>)}</select>}{def.statuses&&<select aria-label="Filter by status" className="filter-select" value={statusFilter} onChange={(event)=>setStatusFilter(event.target.value)}><option value="">All statuses</option>{def.statuses.map((status)=><option key={status}>{status}</option>)}</select>}<span className="ml-auto text-xs text-ink-400">{shown.length} {shown.length===1?'record':'records'}</span>{resource==='tasks'&&<div className="flex rounded-lg border border-ink-200 bg-white p-1"><button aria-label="Board view" className={`icon-button ${layout==='board'?'bg-ink-100':''}`} onClick={()=>setLayout('board')}><LayoutGrid size={16}/></button><button aria-label="Table view" className={`icon-button ${layout==='table'?'bg-ink-100':''}`} onClick={()=>setLayout('table')}><List size={16}/></button></div>}</div>
    {resource==='sites'&&shown.length>0?<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{pageItems.map((site)=><Card key={String(site._id)}><div className="site-cover"><Building2 size={43} strokeWidth={1.2}/><span className="site-cover-label">MAPLE PROJECT / {String(site._id).slice(-4).toUpperCase()}</span><div className="absolute right-4 top-4"><Badge>{String(site.status)}</Badge></div></div><div className="p-5"><h2 className="text-lg font-semibold">{String(site.siteName)}</h2><p className="mt-2 flex items-center gap-1.5 text-xs text-ink-500"><MapPin size={13}/>{String(site.location)}</p><div className="my-5">{renderValue(site,'progress')}</div><div className="grid grid-cols-2 gap-4 border-t border-ink-100 pt-4 text-xs"><div><p className="text-ink-400">Contract budget</p><p className="mt-1 font-semibold">{formatCurrency(Number(site.budget))}</p></div><div><p className="text-ink-400">Target completion</p><p className="mt-1 font-semibold">{renderValue(site,'expectedEndDate')}</p></div></div><p className="mt-4 text-xs text-ink-500">{String(site.clientName)} · {String(site.managerName||'Manager not assigned')}</p>{canEdit&&<div className="mt-5 flex gap-2"><button className="secondary-button flex-1 justify-center" onClick={()=>openForm(site)}><Pencil size={14}/>Update site</button>{canDelete&&<button aria-label={`Delete ${site.siteName}`} className="icon-button text-signal-red" onClick={()=>setDeleteId(String(site._id))}><Trash2 size={15}/></button>}</div>}</div></Card>)}</div>:
    resource==='tasks'&&layout==='board'&&shown.length>0?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{def.statuses?.map((status)=><section key={status} className="rounded-xl border border-ink-200/70 bg-ink-100/40 p-3"><div className="mb-4 flex items-center justify-between px-1"><h2 className="text-xs font-semibold">{status}</h2><span className="rounded bg-white px-2 py-0.5 text-[11px] text-ink-500">{shown.filter((record)=>record.status===status).length}</span></div><div className="space-y-3">{shown.filter((record)=>record.status===status).map((task)=><article key={String(task._id)} className="rounded-xl border border-ink-200 bg-white p-4 shadow-panel"><div className="mb-3 flex justify-between"><Badge>{String(task.priority)}</Badge>{canEdit&&<button aria-label={`Edit ${task.title}`} className="text-ink-400" onClick={()=>openForm(task)}><Pencil size={14}/></button>}</div><h3 className="text-sm font-semibold leading-5">{String(task.title)}</h3><p className="mt-2 text-xs text-ink-400">{siteName(task.site as Relation)}</p>{!!task.description&&<p className="mt-3 text-xs leading-5 text-ink-500">{String(task.description)}</p>}<div className="mt-4 flex items-center justify-between border-t border-ink-100 pt-3 text-[11px] text-ink-500"><span>{workerName(task.assignedTo as Relation)}</span><span>{renderValue(task,'dueDate')}</span></div><select aria-label={`Status for ${task.title}`} className="field-input mt-3 text-xs" disabled={busyId===task._id} value={String(task.status)} onChange={(event)=>void changeStatus(task,event.target.value)}>{def.statuses?.map((value)=><option key={value}>{value}</option>)}</select></article>)}{!shown.some((record)=>record.status===status)&&<p className="rounded-lg border border-dashed border-ink-200 p-5 text-center text-xs text-ink-400">No tasks here</p>}</div></section>)}</div>:
    <Card>{shown.length===0?<EmptyState title={search||siteFilter||statusFilter?'No matching records':`No ${resource} yet`} detail={data.sites.length===0&&resource!=='sites'?'Create a site or ask your workspace owner to assign one before adding site records.':`Add your first ${def.singular} to begin. Records are saved to your workspace.`} action={allowNew?<button className="primary-button" onClick={()=>openForm()}><Plus size={16}/>Add {def.singular}</button>:undefined}/>:<div className="table-scroll"><table className="data-table"><thead><tr>{columns.map((column,index)=><th key={column.label} aria-sort={sort.key===def.columns[index]?(sort.descending?'descending':'ascending'):'none'}><button className="flex items-center gap-2" onClick={()=>setSort({key:def.columns[index],descending:sort.key===def.columns[index]?!sort.descending:false})}>{column.label}<span aria-hidden="true">{sort.key===def.columns[index]?(sort.descending?'↓':'↑'):'↕'}</span></button></th>)}{(canEdit||resource==='tasks')&&<th>Actions</th>}</tr></thead><tbody>{pageItems.map((record)=><tr key={String(record._id)}>{columns.map((column)=><td key={column.label}>{column.render(record)}</td>)}{(canEdit||resource==='tasks')&&<td><div className="flex items-center gap-1">{resource==='tasks'&&role==='worker'?<select aria-label={`Status for ${record.title}`} className="filter-select" value={String(record.status)} disabled={busyId===record._id} onChange={(event)=>void changeStatus(record,event.target.value)}>{def.statuses?.map((value)=><option key={value}>{value}</option>)}</select>:<>{canEdit&&!(resource==='team'&&record._id===user?._id)&&<button className="icon-button" aria-label={`Edit ${record.title||record.companyName||record.fullName||record.materialName||record.description||record.name}`} onClick={()=>openForm(record)}><Pencil size={15}/></button>}{canDelete&&resource!=='team'&&<button aria-label="Delete record" className="icon-button text-signal-red" onClick={()=>setDeleteId(String(record._id))}><Trash2 size={15}/></button>}{resource==='team'&&record._id!==user?._id&&<button className="secondary-button text-xs" onClick={()=>setResetPasswordId(String(record._id))}>Reset password</button>}{resource==='team'&&record._id!==user?._id&&<button className="secondary-button text-xs" disabled={busyId===record._id} onClick={async()=>{setBusyId(String(record._id));try{await save('team',{active:record.active===false},String(record._id));}catch(err){setActionError(err instanceof Error?err.message:'Could not update account.');}finally{setBusyId('');}}}>{busyId===record._id?<Loader2 size={13} className="animate-spin"/>:null}{record.active===false?'Enable':'Disable'}</button>}</>}</div></td>}</tr>)}</tbody></table></div>}</Card>}
    {sorted.length>pageSize&&!(resource==='tasks'&&layout==='board')&&<div className="mt-5 flex items-center justify-between gap-3 text-xs text-ink-500"><span>{(currentPage-1)*pageSize+1}–{Math.min(currentPage*pageSize,sorted.length)} of {sorted.length}</span><div className="flex items-center gap-3"><button className="secondary-button" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Previous</button><span>Page {currentPage} of {pages}</span><button className="secondary-button" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Next</button></div></div>}
    {resetPasswordId&&<RecordForm title="Reset team password" description="Set a temporary password and share it privately with this team member. They must change it on sign-in; existing sessions are revoked." fields={[{key:'password',label:'Temporary password',type:'password',required:true},{key:'confirmation',label:'Confirm password',type:'password',required:true}]} onClose={()=>setResetPasswordId(undefined)} onSave={async(values)=>{if(values.password!==values.confirmation)throw new Error('Passwords do not match.');await apiRequest(`/team/${resetPasswordId}/password`,{method:'PUT',body:JSON.stringify({password:values.password})});await refresh();}}/>}
    {form&&<RecordForm title={`${editingId?'Edit':'New'} ${def.singular}`} description={resource==='team'?'Worker accounts must be linked to a registered worker. Managers receive only selected sites.':undefined} fields={fields} initial={form} onClose={()=>setForm(null)} onSave={async(values)=>{
      const payload={...values};
      ['_id','createdAt','organizationId','createdBy','reportedBy','statusOverride'].forEach((key)=>delete payload[key]);
      if(resource==='workers'){if(!payload.email)delete payload.email;if(!payload.assignedSite)payload.assignedSite=null;}
      if(resource==='tasks'&&!payload.assignedTo)payload.assignedTo=null;
      if(resource==='reports'&&role==='worker')payload.type='Safety inspection';if(resource==='reports'&&payload.hoursWorked==='')delete payload.hoursWorked;
      if(resource==='expenses'&&payload.status==='Paid'&&(!payload.paymentMethod||!payload.paidTo))throw new Error('Provide the payee and payment method before marking an expense Paid.');
      if(resource==='team'){payload.assignedSites=Array.isArray(payload.assignedSites)?payload.assignedSites:[];if(!editingId&&payload.role==='worker'&&!payload.workerId)throw new Error('Select the worker profile for this login account.');if(payload.role==='worker')payload.assignedSites=[];if(payload.role==='hr'&&!(payload.assignedSites as string[]).length)throw new Error('Assign at least one site to the manager.');}
      if(resource==='documents'&&payload.hasAttachment&&!payload.attachment&&payload.fileName===''&&!payload.url)throw new Error('Provide a link or upload a replacement file when removing an attachment.');
      if(resource==='documents'&&!payload.url&&!payload.attachment&&!payload.hasAttachment)throw new Error('Provide a document link or upload a file.');
      await save(resource,payload,editingId);
    }}/>} {deleteId&&<ConfirmDialog title={`Delete ${def.singular}?`} message="This record will be permanently removed from this workspace. Sites, workers with operational history and paid expenses are protected from deletion." onClose={()=>setDeleteId(undefined)} onConfirm={()=>remove(resource,deleteId)}/>}
  </div>;
}
